//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAR_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileLibrary
    {
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public string OFileName { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FileExt { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public Nullable<int> TicketID { get; set; }
        public string ProjectType { get; set; }
        public int FileID { get; set; }
    }
}
