//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAR_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicketData
    {
        public int CustomerID { get; set; }
        public int TicketID { get; set; }
        public string TicketNumber { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public int UpdatedBy { get; set; }
        public int UserID { get; set; }
        public int TechID { get; set; }
        public string UpdateDescription { get; set; }
        public string ProjectType { get; set; }
        public int ResponseID { get; set; }
    }
}
