//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAR_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicketStatusIndex
    {
        public int TicketStatusID { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<int> UserAccountTypeID { get; set; }
        public Nullable<int> StatusOrder { get; set; }
    }
}
